data_path: "../contest_baseline_code/data"
prompt_path: "prompt/base_cot_eng.yaml"
test_output_dir: "outputs"
model:
  name_or_path: "Qwen2.5-7B-Instruct-2/checkpoint-5319"
  chat_template: True
  output_dir: "Qwen2.5-7B-Instruct-2"
  torch_dtype: float16
  lr_scheduler: "cosine"
  batch_size: 1
  epochs: 3
  learning_rate: 2e-5
  weight_decay: 0.01
peft:
  r: 6
  lora_alpha: 8
  lora_dropout: 0.05
  target_modules: ["q_proj", "k_proj"]
  bias: "none"
  task_type: "CAUSAL_LM"
quantization:
  4bit_or_8bit: 4
  compute_dtype: float16
  double_quant: True
  quant_type: nf4